apiVersion: v1
kind: Service
metadata:
  name: akash-hostname-operator
  namespace: akash-services
  labels:
    app.kubernetes.io/instance: hostname-operator
    app.kubernetes.io/name: akash-hostname-operator
    app.kubernetes.io/version: 0.16.6
spec:
  type: ClusterIP
  ports:
    - port: 8188
      name: status
  selector:
    app.kubernetes.io/instance: hostname-operator
    app.kubernetes.io/name: akash-hostname-operator
