apiVersion: v1
kind: ServiceAccount
metadata:
  name: akash-hostname-operator
  namespace: akash-services
  labels:
    app.kubernetes.io/instance: hostname-operator
    app.kubernetes.io/name: akash-hostname-operator
    app.kubernetes.io/version: 0.16.6
  annotations: {}
